server:
  port: 9333

web:
#  IP: 182.247.245.27
  IP: localhost
  database: jijia_production
  redisIP: localhost
#  database: jijia_test
#  IP: localhost

spring:
  application:
    name: user
  datasource:
        username: root
        password: '%#$123456jijia'
        url: jdbc:mysql://${web.IP}:3306/${web.database}?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  redis:
    host: ${web.redisIP}
    database: 0
    port: 6379
    timeout: 100



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://boos3.com:9993/eureka/,http://boos2.com:9992/eureka/,http://boos1.com:9991/eureka/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config.refresh-mapper: true

info:
  app.name: $project.name$
  company.name: baiyajin
  build.artifactId: $project.artifactId$
  build.version: $project.version$