server:
  port: 9102

web:
  #IP: 192.168.8.19
  #IP: 182.247.245.27
  IP: 127.0.0.1
  database: jijia_test
  #database: matdemo


spring:
  application:
    name: materials
#  redis:
#    host: 182.247.245.27
#    password: baiyajin
#    database: 0
#    port: 6379
#    timeout: 100
  datasource:
    username: root
    password: root
    #password: '%#$123456jijia'
    url: jdbc:mysql://${web.IP}:3306/${web.database}?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  redis:
    database: 0
    host: 127.0.0.1
   # password:
    port: 6379

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:9991/eureka/




mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  typeAliasesPackage: com.baiyajin.entity.bean
  global-config.refresh-mapper: true


info:
  app.name: ${project.name}$
  company.name: baiyajin
  build.artifactId: $project.artifactId$
  build.version: $project.version$
#
logging:
  level:
     com.baiyajin.materials.mapper : debug