server:
  port: 9004

web:
  IP: 182.247.245.27
  database: jijia_production
#  database: jijia_test
#  IP: localhost

spring:
  application:
    name: MATERIALS
#  redis:
#    host: 182.247.245.27
#    password: baiyajin
#    database: 0
#    port: 6379
#    timeout: 100
  datasource:
        username: root
        password: '%#$123456jijia'
        url: jdbc:mysql://${web.IP}:3306/${web.database}?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/




mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  typeAliasesPackage: com.baiyajin.entity.bean
  global-config.refresh-mapper: true


