server:
    port: 9992

eureka:
    instance:
#        hostname: localhost
        hostname: boos2
        prefer-ip-address: true
        instance-id: boss2
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
#            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            defaultZone: http://boos1:9991/eureka/,http://boos3:9993/eureka/

info:
    app.name: $project.name$
    company.name: baiyajin
    build.artifactId: $project.artifactId$
    build.version: $project.version$