server:
  port: 9220

web:
#  IP: 182.247.245.27
  IP: 192.168.8.19
#  database: jijia_production
  database: jijia_test
#  IP: localhost

spring:
  application:
    name: controller
  datasource:
        username: root
        password: '%#$123456jijia'
        url: jdbc:mysql://${web.IP}:3306/${web.database}?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        dbcp2:
          validation-query: SELECT 1
          testWhileIdle: true
          testOnBorrow: true
          testOnReturn: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: controller
  client:
    service-url:
      defaultZone: http://boos3.com:9993/eureka/,http://boos2.com:9992/eureka/,http://boos1.com:9991/eureka/



info:
  app.name: $project.name$
  company.name: baiyajin
  build.artifactId: $project.artifactId$
  build.version: $project.version$