server:
    port: 9991
#    port: 9992
#    port: 9993

eureka:
    instance:
#        hostname: localhost
        hostname: boos1
#        hostname: boos2
#        hostname: boos3
        prefer-ip-address: true
        instance-id: boss1
#        instance-id: boss2
#        instance-id: boss3
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
#            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            defaultZone: http://boos2:9992/eureka/,http://boos3:9993/eureka/
#            defaultZone: http://boos1:9991/eureka/,http://boos3:9993/eureka/
#            defaultZone: http://boos1:9991/eureka/,http://boos2:9992/eureka/
info:
    app.name: $project.name$
    company.name: baiyajin
    build.artifactId: $project.artifactId$
    build.version: $project.version$