baiyajin:
  port: 9991
  hostname: boos1.com
  instance-id: boos1.com
  defaultZone: http://boos2.com:9992/eureka/,http://boos3.com:9993/eureka/
spring:
  profiles:
    active: boos1
server:
    port: ${baiyajin.port}

eureka:
    instance:
        hostname: ${baiyajin.hostname}
        prefer-ip-address: true
        instance-id: ${baiyajin.instance-id}
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: ${baiyajin.defaultZone}
info:
    app.name: $project.name$
    company.name: baiyajin
    build.artifactId: $project.artifactId$
    build.version: $project.version$