server:
    port: 9993

eureka:
    instance:
#        hostname: localhost
        hostname: boos
        prefer-ip-address: true
        instance-id: bosse
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
#            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            defaultZone: http://boos1:9991/eureka/,http://boos2:9992/eureka/
info:
    app.name: $project.name$
    company.name: baiyajin
    build.artifactId: $project.artifactId$
    build.version: $project.version$